Keep a copy of hte old version of the file

diff --git a/start-zeronet b/start-zeronet
--- a/start-zeronet
+++ b/start-zeronet
@@ -4,8 +4,12 @@ cd /etc/share/zeronet
 
 mesh_active=$(systemctl is-active zeronet-mesh)
 if [ $mesh_active -eq 'active' ]]; then
-	echo 'zeronet-mesh is active. Cannot start.'
-	exit 1
+    echo 'zeronet-mesh is active. Cannot start.'
+    exit 1
+fi
+
+if [ -f /etc/share/zeronet/src/Site/Site.old ]; then
+    cp /etc/share/zeronet/src/Site/Site.old /etc/share/zeronet/src/Site/Site.py
 fi
 
 if [ ! -d /etc/tor ]; then
diff --git a/start-zeronet-mesh b/start-zeronet-mesh
--- a/start-zeronet-mesh
+++ b/start-zeronet-mesh
@@ -4,13 +4,14 @@ cd /etc/share/zeronet
 
 zeronet_active=$(systemctl is-active zeronet)
 if [ $zeronet_active -eq 'active' ]; then
-	echo 'zeronet is active. Cannot start.'
-	exit 1
+    echo 'zeronet is active. Cannot start.'
+    exit 1
 fi
 
 # Hack to ensure that the file access port is opened
 # This is because zeronet normally relies on an internet site
 # to do this, but on a purely local mesh the internet isn't available
+cp /etc/share/zeronet/src/Site/Site.py /etc/share/zeronet/src/Site/Site.old
 sed -i 's|fileserver_port = 0|fileserver_port = config.fileserver_port\n            sys.modules["main"].file_server.port_opened = True|g' /etc/share/zeronet/src/Site/Site.py
 
 /usr/bin/python zeronet.py --ip_external $(hostname).local --trackers_file /etc/share/zeronet/bootstrap
