Prevent both regular and mash daemons being active at the same time

diff --git a/start-zeronet b/start-zeronet
--- a/start-zeronet
+++ b/start-zeronet
@@ -2,6 +2,12 @@
 
 cd /etc/share/zeronet
 
+mesh_active=$(systemctl is-active zeronet-mesh)
+if [ $mesh_active -eq 'active' ]]; then
+	echo 'zeronet-mesh is active. Cannot start.'
+	exit 1
+fi
+
 if [ ! -d /etc/tor ]; then
     /usr/bin/python zeronet.py
 else
diff --git a/start-zeronet-mesh b/start-zeronet-mesh
--- a/start-zeronet-mesh
+++ b/start-zeronet-mesh
@@ -2,6 +2,12 @@
 
 cd /etc/share/zeronet
 
+zeronet_active=$(systemctl is-active zeronet)
+if [ $zeronet_active -eq 'active' ]; then
+	echo 'zeronet is active. Cannot start.'
+	exit 1
+fi
+
 # Hack to ensure that the file access port is opened
 # This is because zeronet normally relies on an internet site
 # to do this, but on a purely local mesh the internet isn't available
